/**
 * NAME: SampledData
 * DESCRIPTION: Dummy data formatted for the Grubb's calculator. Data to represent the smapled data pulled form PI.
 *              Each row is a unique tag's set of Values between two time stamps.
 */


var SampledData = {


        piTags: [
            {Name: "CAM_DCS:FIC201A2.PV", WebID: "P04fzRUyKOPUK7lpmO6iv2GgozMBAAQVpSMDFQSTAxXENBTV9EQ1M6RklDMjAxQTIuUFY", Description: "P201A2 Disch Flow", MapTo: "", MapToWebID: "", Jetty: "", Analyzer: "", TagType: "Flow", Index: 0},
            {Name: "CAM_DCS:FIC201B2.PV", WebID: "P04fzRUyKOPUK7lpmO6iv2GgpTMBAAQVpSMDFQSTAxXENBTV9EQ1M6RklDMjAxQjIuUFY", Description: "P201B2 Disch Flow", MapTo: "", MapToWebID: "", Jetty: "", Analyzer: "", TagType: "Flow", Index: 0},
            {Name: "CAM_DCS:FIC201C2.PV", WebID: "P04fzRUyKOPUK7lpmO6iv2GgpzMBAAQVpSMDFQSTAxXENBTV9EQ1M6RklDMjAxQzIuUFY", Description: "P201C2 Disch Flow", MapTo: "", MapToWebID: "", Jetty: "", Analyzer: "", TagType: "Flow", Index: 0},
            {Name: "CAM_DCS:FIC201D2.PV", WebID: "P04fzRUyKOPUK7lpmO6iv2Ggnp0AAAQVpSMDFQSTAxXENBTV9EQ1M6RklDMjAxRDIuUFY", Description: "P201D2 Disch Flow", MapTo: "", MapToWebID: "", Jetty: "", Analyzer: "", TagType: "Flow", Index: 0},
            {Name: "CAM_DCS:FIC202B2.PV", WebID: "P04fzRUyKOPUK7lpmO6iv2Ggop0AAAQVpSMDFQSTAxXENBTV9EQ1M6RklDMjAyQjIuUFY", Description: "P202B2 Disch Flow", MapTo: "", MapToWebID: "", Jetty: "", Analyzer: "", TagType: "Flow", Index: 0},
            {Name: "CAM_DCS:FIC202A2.PV", WebID: "P04fzRUyKOPUK7lpmO6iv2GgoJ0AAAQVpSMDFQSTAxXENBTV9EQ1M6RklDMjAyQTIuUFY", Description: "P202A2 Disch Flow", MapTo: "", MapToWebID: "", Jetty: "", Analyzer: "", TagType: "Flow", Index: 0},
            {Name: "CAM_DCS:FIC202C2.PV", WebID: "P04fzRUyKOPUK7lpmO6iv2GgpJ0AAAQVpSMDFQSTAxXENBTV9EQ1M6RklDMjAyQzIuUFY", Description: "P202C2 Disch Flow", MapTo: "", MapToWebID: "", Jetty: "", Analyzer: "", TagType: "Flow", Index: 0},
            {Name: "CAM_DCS:FIC202D2.PV", WebID: "P04fzRUyKOPUK7lpmO6iv2Ggpp0AAAQVpSMDFQSTAxXENBTV9EQ1M6RklDMjAyRDIuUFY", Description: "P202D2 Disch Flow", MapTo: "", MapToWebID: "", Jetty: "", Analyzer: "", TagType: "Flow", Index: 0},
            {Name: "CAM_DCS:FIC203A2.PV", WebID: "P04fzRUyKOPUK7lpmO6iv2GgqJ0AAAQVpSMDFQSTAxXENBTV9EQ1M6RklDMjAzQTIuUFY", Description: "P203A2 Disch Flow", MapTo: "", MapToWebID: "", Jetty: "", Analyzer: "", TagType: "Flow", Index: 0},
            {Name: "CAM_DCS:FIC203B2.PV", WebID: "P04fzRUyKOPUK7lpmO6iv2Ggqp0AAAQVpSMDFQSTAxXENBTV9EQ1M6RklDMjAzQjIuUFY", Description: "P203B2 Disch Flow", MapTo: "", MapToWebID: "", Jetty: "", Analyzer: "", TagType: "Flow", Index: 0},
            {Name: "CAM_DCS:FIC203C2.PV", WebID: "P04fzRUyKOPUK7lpmO6iv2GgrJ0AAAQVpSMDFQSTAxXENBTV9EQ1M6RklDMjAzQzIuUFY", Description: "P203C2 Disch Flow", MapTo: "", MapToWebID: "", Jetty: "", Analyzer: "", TagType: "Flow", Index: 0},
            {Name: "CAM_DCS:FIC203D2.PV", WebID: "P04fzRUyKOPUK7lpmO6iv2Ggrp0AAAQVpSMDFQSTAxXENBTV9EQ1M6RklDMjAzRDIuUFY", Description: "P203D2 Disch Flow", MapTo: "", MapToWebID: "", Jetty: "", Analyzer: "", TagType: "Flow", Index: 0},
            {Name: "CAM:LNG_Ship.Cargo_No", WebID: "P04fzRUyKOPUK7lpmO6iv2GgoAEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DQVJHT19OTw", Description: "Cargo Number", MapTo: "CAM:LNG_Ship.Cargo_No", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgoAEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DQVJHT19OTw", Jetty: "", Analyzer: "", TagType: "", Index: 0},
            {Name: "CAM:LNG_Ship.Sample_Timestamp", WebID: "P04fzRUyKOPUK7lpmO6iv2GgqwEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5TQU1QTEVfVElNRVNUQU1Q", Description: "LOADED SHIP SAMPLE TIMESTAMP", MapTo: "", MapToWebID: "", Jetty: "", Analyzer: "", TagType: "Time", Index: 0},
            {Name: "CAM_DCS:AI1001A_C6", WebID: "P04fzRUyKOPUK7lpmO6iv2GgMQ4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQV9DNg", Description: "NJ Unloading Hexane", MapTo: "CAM:LNG_Ship.C6+", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgnwEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DNis", Jetty: "North", Analyzer: "North", TagType: "Analyzer", Index: 10},
            {Name: "CAM_DCS:AI1001A_ETH", WebID: "P04fzRUyKOPUK7lpmO6iv2GgNA4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQV9FVEg", Description: "NJ Unloading Ethane", MapTo: "CAM:LNG_Ship.C2", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgnQEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DMg", Jetty: "North", Analyzer: "North", TagType: "Analyzer", Index: 4},
            {Name: "CAM_DCS:AI1001A_IPEN", WebID: "P04fzRUyKOPUK7lpmO6iv2GgNg4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQV9JUEVO", Description: "NJ Unloading iPentane", MapTo: "CAM:LNG_Ship.iC5", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgpQEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5JQzU", Jetty: "North", Analyzer: "North", TagType: "Analyzer", Index: 7},
            {Name: "CAM_DCS:AI1001A_IBU", WebID: "P04fzRUyKOPUK7lpmO6iv2GgNQ4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQV9JQlU", Description: "NJ Unloading iButane", MapTo: "CAM:LNG_Ship.iC4", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgpAEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5JQzQ", Jetty: "North", Analyzer: "North", TagType: "Analyzer", Index: 6},
            {Name: "CAM_DCS:AI1001A_METH", WebID: "P04fzRUyKOPUK7lpmO6iv2GgNw4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQV9NRVRI", Description: "NJ Unloading Methane", MapTo: "CAM:LNG_Ship.C1", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgnAEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DMQ", Jetty: "North", Analyzer: "North", TagType: "Analyzer", Index: 3},
            {Name: "CAM_DCS:AI1001A_N2", WebID: "P04fzRUyKOPUK7lpmO6iv2GgOA4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQV9OMg", Description: "NJ Unloading Nitrogen", MapTo: "CAM:LNG_Ship.N2", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgpgEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5OMg", Jetty: "North", Analyzer: "North", TagType: "Analyzer", Index: 1},
            {Name: "CAM_DCS:AI1001A_NPEN", WebID: "P04fzRUyKOPUK7lpmO6iv2GgOg4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQV9OUEVO", Description: "NJ Unloading nPentane", MapTo: "CAM:LNG_Ship.nC5", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgqAEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5OQzU", Jetty: "North", Analyzer: "North", TagType: "Analyzer", Index: 9},
            {Name: "CAM_DCS:AI1001A_NBU", WebID: "P04fzRUyKOPUK7lpmO6iv2GgOQ4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQV9OQlU", Description: "NJ Unloading nButane", MapTo: "CAM:LNG_Ship.nC4", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgpwEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5OQzQ", Jetty: "North", Analyzer: "North", TagType: "Analyzer", Index: 8},
            {Name: "CAM_DCS:AI1001A_PRO", WebID: "P04fzRUyKOPUK7lpmO6iv2GgPA4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQV9QUk8", Description: "NJ Unloading Propane", MapTo: "CAM:LNG_Ship.C3", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgngEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DMw", Jetty: "North", Analyzer: "North", TagType: "Analyzer", Index: 5},
            {Name: "CAM_DCS:AI1001A_CO2", WebID: "P04fzRUyKOPUK7lpmO6iv2GgMg4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQV9DTzI", Description: "NJ Unloading Carbon Dioxide", MapTo: "CAM:LNG_Ship.CO2", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgoQEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DTzI", Jetty: "North", Analyzer: "North", TagType: "Analyzer", Index: 2},
            {Name: "CAM_DCS:AI1001B_C6", WebID: "P04fzRUyKOPUK7lpmO6iv2GgQA4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQl9DNg", Description: "SJ Unloading Hexane", MapTo: "CAM:LNG_Ship.C6+", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgnwEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DNis", Jetty: "South", Analyzer: "North", TagType: "Analyzer", Index: 10},
            {Name: "CAM_DCS:AI1001B_ETH", WebID: "P04fzRUyKOPUK7lpmO6iv2GgQw4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQl9FVEg", Description: "SJ Unloading Ethane", MapTo: "CAM:LNG_Ship.C2", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgnQEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DMg", Jetty: "South", Analyzer: "North", TagType: "Analyzer", Index: 4},
            {Name: "CAM_DCS:AI1001B_IPEN", WebID: "P04fzRUyKOPUK7lpmO6iv2GgRQ4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQl9JUEVO", Description: "SJ Unloading iPentane", MapTo: "CAM:LNG_Ship.iC5", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgpQEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5JQzU", Jetty: "South", Analyzer: "North", TagType: "Analyzer", Index: 7},
            {Name: "CAM_DCS:AI1001B_IBU", WebID: "P04fzRUyKOPUK7lpmO6iv2GgRA4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQl9JQlU", Description: "SJ Unloading iButane", MapTo: "CAM:LNG_Ship.iC4", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2Gg8bsAAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5JQzQ", Jetty: "South", Analyzer: "North", TagType: "Analyzer", Index: 6},
            {Name: "CAM_DCS:AI1001B_METH", WebID: "P04fzRUyKOPUK7lpmO6iv2GgRg4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQl9NRVRI", Description: "SJ Unloading Methane", MapTo: "CAM:LNG_Ship.C1", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgnAEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DMQ", Jetty: "South", Analyzer: "North", TagType: "Analyzer", Index: 3},
            {Name: "CAM_DCS:AI1001B_N2", WebID: "P04fzRUyKOPUK7lpmO6iv2GgRw4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQl9OMg", Description: "SJ Unloading Nitrogen", MapTo: "CAM:LNG_Ship.N2", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgpgEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5OMg", Jetty: "South", Analyzer: "North", TagType: "Analyzer", Index: 1},
            {Name: "CAM_DCS:AI1001B_NPEN", WebID: "P04fzRUyKOPUK7lpmO6iv2GgSQ4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQl9OUEVO", Description: "SJ Unloading nPentane", MapTo: "CAM:LNG_Ship.nC5", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgqAEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5OQzU", Jetty: "South", Analyzer: "North", TagType: "Analyzer", Index: 9},
            {Name: "CAM_DCS:AI1001B_NBU", WebID: "P04fzRUyKOPUK7lpmO6iv2GgSA4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQl9OQlU", Description: "SJ Unloading nButane", MapTo: "CAM:LNG_Ship.nC4", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgpwEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5OQzQ", Jetty: "South", Analyzer: "North", TagType: "Analyzer", Index: 8},
            {Name: "CAM_DCS:AI1001B_PRO", WebID: "P04fzRUyKOPUK7lpmO6iv2GgSw4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQl9QUk8", Description: "SJ Unloading Propane", MapTo: "CAM:LNG_Ship.C3", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgngEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DMw", Jetty: "South", Analyzer: "North", TagType: "Analyzer", Index: 5},
            {Name: "CAM_DCS:AI1001B_CO2", WebID: "P04fzRUyKOPUK7lpmO6iv2GgQQ4AAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMDAxQl9DTzI", Description: "SJ Unloading Carbon Dioxide", MapTo: "CAM:LNG_Ship.CO2", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgoQEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DTzI", Jetty: "South", Analyzer: "North", TagType: "Analyzer", Index: 2},
            {Name: "CAM_DCS:AI1101A9", WebID: "P04fzRUyKOPUK7lpmO6iv2GgOBMAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQTk", Description: "SJ Unloading Hexane", MapTo: "CAM:LNG_Ship.C6+", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgnwEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DNis", Jetty: "South", Analyzer: "South", TagType: "Analyzer", Index: 10},
            {Name: "CAM_DCS:AI1101A3", WebID: "P04fzRUyKOPUK7lpmO6iv2GgMhMAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQTM", Description: "SJ Unloading Ethane", MapTo: "CAM:LNG_Ship.C2", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgnQEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DMg", Jetty: "South", Analyzer: "South", TagType: "Analyzer", Index: 4},
            {Name: "CAM_DCS:AI1101A7", WebID: "P04fzRUyKOPUK7lpmO6iv2GgNhMAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQTc", Description: "SJ Unloading iPentane", MapTo: "CAM:LNG_Ship.iC5", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgpQEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5JQzU", Jetty: "South", Analyzer: "South", TagType: "Analyzer", Index: 7},
            {Name: "CAM_DCS:AI1101A5", WebID: "P04fzRUyKOPUK7lpmO6iv2GgNBMAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQTU", Description: "SJ Unloading iButane", MapTo: "CAM:LNG_Ship.iC4", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2Gg8bsAAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5JQzQ", Jetty: "South", Analyzer: "South", TagType: "Analyzer", Index: 6},
            {Name: "CAM_DCS:AI1101A2", WebID: "P04fzRUyKOPUK7lpmO6iv2GgMRMAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQTI", Description: "SJ Unloading Methane", MapTo: "CAM:LNG_Ship.C1", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgnAEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DMQ", Jetty: "South", Analyzer: "South", TagType: "Analyzer", Index: 3},
            {Name: "CAM_DCS:AI1101A1", WebID: "P04fzRUyKOPUK7lpmO6iv2GgMBMAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQTE", Description: "SJ Unloading Nitrogen", MapTo: "CAM:LNG_Ship.N2", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgpgEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5OMg", Jetty: "South", Analyzer: "South", TagType: "Analyzer", Index: 1},
            {Name: "CAM_DCS:AI1101A8", WebID: "P04fzRUyKOPUK7lpmO6iv2GgNxMAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQTg", Description: "SJ Unloading nPentane", MapTo: "CAM:LNG_Ship.nC5", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgqAEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5OQzU", Jetty: "South", Analyzer: "South", TagType: "Analyzer", Index: 9},
            {Name: "CAM_DCS:AI1101A6", WebID: "P04fzRUyKOPUK7lpmO6iv2GgNRMAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQTY", Description: "SJ Unloading nButane", MapTo: "CAM:LNG_Ship.nC4", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgpwEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5OQzQ", Jetty: "South", Analyzer: "South", TagType: "Analyzer", Index: 8},
            {Name: "CAM_DCS:AI1101A4", WebID: "P04fzRUyKOPUK7lpmO6iv2GgMxMAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQTQ", Description: "SJ Unloading Propane", MapTo: "CAM:LNG_Ship.C3", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgngEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DMw", Jetty: "South", Analyzer: "South", TagType: "Analyzer", Index: 5},
            {Name: "CAM_DCS:AI1101A_CO2.PV", WebID: "P04fzRUyKOPUK7lpmO6iv2GgxlwAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQV9DTzIuUFY", Description: "SJ Unloading Carbon Dioxide", MapTo: "CAM:LNG_Ship.CO2", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgoQEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DTzI", Jetty: "South", Analyzer: "South", TagType: "Analyzer", Index: 2},
            {Name: "CAM_DCS:AI1101B1", WebID: "P04fzRUyKOPUK7lpmO6iv2GgORMAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQjE", Description: "North Jetty Nitrogen Composition", MapTo: "CAM:LNG_Ship.N2", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgpgEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5OMg", Jetty: "North", Analyzer: "South", TagType: "Analyzer", Index: 1},
            {Name: "CAM_DCS:AI1101B2", WebID: "P04fzRUyKOPUK7lpmO6iv2GgOhMAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQjI", Description: "North Jetty Methane Composition", MapTo: "CAM:LNG_Ship.C1", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgnAEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DMQ", Jetty: "North", Analyzer: "South", TagType: "Analyzer", Index: 3},
            {Name: "CAM_DCS:AI1101B3", WebID: "P04fzRUyKOPUK7lpmO6iv2GgOxMAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQjM", Description: "North Jetty Ethane Composition", MapTo: "CAM:LNG_Ship.C2", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgnQEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DMg", Jetty: "North", Analyzer: "South", TagType: "Analyzer", Index: 4},
            {Name: "CAM_DCS:AI1101B4", WebID: "P04fzRUyKOPUK7lpmO6iv2GgPBMAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQjQ", Description: "North Jetty Propane Composition", MapTo: "CAM:LNG_Ship.C3", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgngEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DMw", Jetty: "North", Analyzer: "South", TagType: "Analyzer", Index: 5},
            {Name: "CAM_DCS:AI1101B5", WebID: "P04fzRUyKOPUK7lpmO6iv2GgPRMAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQjU", Description: "North Jetty iButane Composition", MapTo: "CAM:LNG_Ship.iC4", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2Gg8bsAAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5JQzQ", Jetty: "North", Analyzer: "South", TagType: "Analyzer", Index: 6},
            {Name: "CAM_DCS:AI1101B6", WebID: "P04fzRUyKOPUK7lpmO6iv2GgPhMAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQjY", Description: "North Jetty nButane Composition", MapTo: "CAM:LNG_Ship.nC4", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgpwEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5OQzQ", Jetty: "North", Analyzer: "South", TagType: "Analyzer", Index: 8},
            {Name: "CAM_DCS:AI1101B7", WebID: "P04fzRUyKOPUK7lpmO6iv2GgPxMAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQjc", Description: "North Jetty iPentane Composition", MapTo: "CAM:LNG_Ship.iC5", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgpQEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5JQzU", Jetty: "North", Analyzer: "South", TagType: "Analyzer", Index: 7},
            {Name: "CAM_DCS:AI1101B8", WebID: "P04fzRUyKOPUK7lpmO6iv2GgQBMAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQjg", Description: "North Jetty nPentane Composition", MapTo: "CAM:LNG_Ship.nC5", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgqAEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5OQzU", Jetty: "North", Analyzer: "South", TagType: "Analyzer", Index: 9},
            {Name: "CAM_DCS:AI1101B9", WebID: "P04fzRUyKOPUK7lpmO6iv2GgQRMAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQjk", Description: "North Jetty nHexane Composition", MapTo: "CAM:LNG_Ship.C6+", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgnwEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DNis", Jetty: "North", Analyzer: "South", TagType: "Analyzer", Index: 10},
            {Name: "CAM_DCS:AI1101B_CO2.PV", WebID: "P04fzRUyKOPUK7lpmO6iv2Gg2FwAAAQVpSMDFQSTAxXENBTV9EQ1M6QUkxMTAxQl9DTzIuUFY", Description: "CARBON DIOXIDE - STREAM 2", MapTo: "CAM:LNG_Ship.CO2", MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgoQEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5DTzI", Jetty: "North", Analyzer: "South", TagType: "Analyzer", Index: 2}
        ],

    limsTags : [
        { Name: "AF_NORTH_H2S.CURRENT_VALUE",WebID: "P04fzRUyKOPUK7lpmO6iv2GgaTgBAAQVpSMDFQSTAxXEFGX05PUlRIX0gyUy5DVVJSRU5UX1ZBTFVF",Description: "LIMS: North Jetty Hydrogen Sulfide sample",MapTo: "CAM:LNG_Ship.H2S",MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgogEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5IMlM",Jetty: "North",TagType: "LIMS"},
        { Name: "AF_NORTH_MERCURY.CURRENT_VALUE",WebID: "P04fzRUyKOPUK7lpmO6iv2GgajgBAAQVpSMDFQSTAxXEFGX05PUlRIX01FUkNVUlkuQ1VSUkVOVF9WQUxVRQ",Description: "LIMS: North Jetty Mercury sample",MapTo: "CAM:LNG_Ship.Hg",MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgowEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5IRw",Jetty: "North",TagType: "LIMS"},
        { Name: "AF_NORTH_TOT_SULFUR.CURRENT_VALUE",WebID: "P04fzRUyKOPUK7lpmO6iv2GgazgBAAQVpSMDFQSTAxXEFGX05PUlRIX1RPVF9TVUxGVVIuQ1VSUkVOVF9WQUxVRQ",Description: "LIMS: North Jetty Sulfur sample",MapTo: "CAM:LNG_Ship.S",MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgqQEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5T",Jetty: "North",TagType: "LIMS"},
        { Name: "AF_SOUTH_H2S.CURRENT_VALUE",WebID: "P04fzRUyKOPUK7lpmO6iv2GgbjgBAAQVpSMDFQSTAxXEFGX1NPVVRIX0gyUy5DVVJSRU5UX1ZBTFVF",Description: "LIMS: South Jetty Hydrogen Sulfide sample",MapTo: "CAM:LNG_Ship.H2S",MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgogEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5IMlM",Jetty: "South",TagType: "LIMS"},
        { Name: "AF_SOUTH_MERCURY.CURRENT_VALUE",WebID: "P04fzRUyKOPUK7lpmO6iv2GgbTgBAAQVpSMDFQSTAxXEFGX1NPVVRIX01FUkNVUlkuQ1VSUkVOVF9WQUxVRQ",Description: "LIMS: South Jetty Mercury sample",MapTo: "CAM:LNG_Ship.Hg",MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgowEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5IRw",Jetty: "South",TagType: "LIMS"},
        { Name: "AF_SOUTH_TOT_SULFUR.CURRENT_VALUE",WebID: "P04fzRUyKOPUK7lpmO6iv2GgbDgBAAQVpSMDFQSTAxXEFGX1NPVVRIX1RPVF9TVUxGVVIuQ1VSUkVOVF9WQUxVRQ",Description: "LIMS: South Jetty Sulfur sample",MapTo: "CAM:LNG_Ship.S",MapToWebID: "P04fzRUyKOPUK7lpmO6iv2GgqQEBAAQVpSMDFQSTAxXENBTTpMTkdfU0hJUC5T",Jetty: "South",TagType: "LIMS"},
    ],
    

    getSamplesForRow : function(row){
        return this.samples[row]
    },

    // getMappedTag : function(name) {
    //     return piTag.filter(obj => {
    //         return obj.name === name
    //       }).MapTo;
    // }
}